sudo: false
language: go
go:
- 1.16.6
install:
- scripts/bootstrap
before_script:
- export PATH="$PATH:$HOME/bin:$GOPATH/bin:$TRAVIS_BUILD_DIR/bin"
- scripts/install
script:
- scripts/test
before_deploy:
- scripts/dist
deploy:
  provider: releases
  api_key:
    secure: bJ+VYsIhJo+wS9Ze2Y2O+EbqajTK7LOItDXcAqc9atzmAdiRsNSq8D+0zJQWYOmTEuUgXwNq2jmaGx8rmE4koJYLjB9Xq9vEWRPa+PX6dJW0uLUqc5ZNLBLLRAIVHxon6ujk4FwkFMypEHnuV7QDpBqbMVmdlyyZAXGuPFsTr8+jUq88o2vjDNctGZisH4CR/NnGrQQsrJ2MZAhmRaE2YXhKxZA/efGjXkRfD0zu79AQzdTJaGiSeJmhyRDTSGZRjvKRbMJPjgzqFT2bLuAxizb5esO9isULBDejeh5DS9L4l5GcwbeZzQARYHL4HdRi7hS1B6ciFHIiIq7+eYO77dlqXaoOrfhobXgE3z/T6LthOn8oefeeW3BtJjs28MYlcBHM8Mc4J6ZAcC7IgfjCRrWwTCY6hFRzPNOD3Rad8Hwqt6nKizeirhUeAZ6vJ3L08iO/tY0opgyVFfOF1aLSyN3m04jpUhbmSVjo7VXk/rFkf/mtuJZZWzC+NXz/8IDkM4Gylw4qr5ehn3pZnY78YUdRXUfl8EtGXq7yyqBoMZAMIgC929VGg6AOT9zMsKs2KO18LLWF5pB1za5hdsPC6X9EOrJh0usZYgJCy0+rfKLsyLYFDSWsVxKvS/DHyW0MNnA3MCL4MJ8q1GSoMSKfPbUKT18L58c/LOzjoLPPsRs=
  file_glob: true
  file: 'dist/*.tar.gz'
  skip_cleanup: true
  on:
    repo: git-duet/git-duet
    tags: true
notifications:
  email: jesse.szwedko@gmail.com
